apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-client
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: node-client
    spec:
      containers:
        - image: jgking2/node-web-app
          imagePullPolicy: Always
          name: node-client
          ports:
            - containerPort: 8080
